
/* SMASHDUMP_R81_SUCCESSOR_GAUNTLET_SEASON_BANNER_ADAPTER */
(()=>{'use strict';const marker='SMASHDUMP_R81_SUCCESSOR_GAUNTLET_SEASON_BANNER_ADAPTER';if(globalThis.__SMASHDUMP_R81_GAUNTLET_BANNER_ADAPTER__)return;
 const seasonAssets={"gauntlet-season:1000000001":{"fallback_url":"../../../assets/current/49b8829a056f42ddab2db2fb69c5180865f01bd2af146f7c7946d6caf3c9c640.webp","logical_path":"UI/Download/banner/quest/prt_bnr_quest_1004001","sha256":"49b8829a056f42ddab2db2fb69c5180865f01bd2af146f7c7946d6caf3c9c640","source_table":"m_event_survival","url":"../../../assets/current/49b8829a056f42ddab2db2fb69c5180865f01bd2af146f7c7946d6caf3c9c640.webp"},"gauntlet-season:1000000002":{"fallback_url":"../../../assets/current/3e2583927cb6d8ccd971a5ec08c16e787f71816d8e81b4033a31d0b011101e67.webp","logical_path":"UI/Download/banner/quest/prt_bnr_quest_1004005","sha256":"3e2583927cb6d8ccd971a5ec08c16e787f71816d8e81b4033a31d0b011101e67","source_table":"m_event_survival","url":"../../../assets/current/3e2583927cb6d8ccd971a5ec08c16e787f71816d8e81b4033a31d0b011101e67.webp"},"gauntlet-season:1000000003":{"fallback_url":"../../../assets/current/35c1be5b88ebb980603f9f97d6d5c1bde841fd019f9e43ff00b805108d385fde.webp","logical_path":"UI/Download/banner/quest/prt_bnr_quest_1004009","sha256":"35c1be5b88ebb980603f9f97d6d5c1bde841fd019f9e43ff00b805108d385fde","source_table":"m_event_survival","url":"../../../assets/current/35c1be5b88ebb980603f9f97d6d5c1bde841fd019f9e43ff00b805108d385fde.webp"},"gauntlet-season:1000000004":{"fallback_url":"../../../assets/current/63f1e3f3d2217d6c96626a1143f07153a2cee6d17dc1c8beb67e09efcd16c2cc.webp","logical_path":"UI/Download/banner/quest/prt_bnr_quest_1004013","sha256":"63f1e3f3d2217d6c96626a1143f07153a2cee6d17dc1c8beb67e09efcd16c2cc","source_table":"m_event_survival","url":"../../../assets/current/63f1e3f3d2217d6c96626a1143f07153a2cee6d17dc1c8beb67e09efcd16c2cc.webp"},"gauntlet-season:1000000005":{"fallback_url":"../../../assets/current/662121bd5831659d14aeced07581386379f1c4135e6a7c5a68b8bd3610c4e939.webp","logical_path":"UI/Download/banner/quest/prt_bnr_quest_1005013","sha256":"662121bd5831659d14aeced07581386379f1c4135e6a7c5a68b8bd3610c4e939","source_table":"m_event_survival","url":"../../../assets/current/662121bd5831659d14aeced07581386379f1c4135e6a7c5a68b8bd3610c4e939.webp"}};
 const isCurrent=()=>{const s=globalThis.__SMASHDUMP_ENCYCLOPEDIA_ACTIVE_SNAPSHOT__;return s&&!(/frozen/i.test(String(s.kind||s.app_mode||''))||s.data_root_mode==='accepted_root')};
 const assetFor=key=>{const a=seasonAssets[String(key||'')];return a&&/^[0-9a-f]{64}$/i.test(String(a.sha256||''))?a:null};
 const put=(summary,asset,role)=>{if(!summary||!asset)return false;const sha=String(asset.sha256).toLowerCase(),src=String(asset.url||`../../../assets/current/${sha}.webp`),fallback=String(asset.fallback_url||`assets/game/${sha}.png`);let img=summary.querySelector(':scope > .s3r513r9-summary-art');if(img&&img.dataset.r81SuccessorSeason!=='1')return true;if(!img){img=document.createElement('img');img.className='s3r513r9-summary-art';img.alt='';img.loading='lazy';img.decoding='async';img.draggable=false;img.dataset.r81SuccessorSeason='1';summary.prepend(img)}img.dataset.sha256=sha;img.dataset.logicalPath=String(asset.logical_path||'');img.dataset.r513r9Role=role;img.onerror=()=>{if(fallback&&img.dataset.fallbackApplied!=='1'){img.dataset.fallbackApplied='1';img.src=fallback}else img.remove()};if(img.getAttribute('src')!==src){img.dataset.fallbackApplied='0';img.src=src}summary.classList.add('s3r513r9-has-art');return true};
 const patch=()=>{if(!isCurrent())return false;const list=document.getElementById('entityList');if(!list)return false;const seasons=[...list.querySelectorAll('details[data-r513r2-node^="gauntlet-season:"]')];for(const details of seasons){const key=String(details.dataset.r513r2Node||''),asset=assetFor(key);if(asset)put(details.querySelector(':scope > summary'),asset,'season')}const parent=list.querySelector('details[data-r513r2-node="collection:gauntlet"]');if(parent){const open=seasons.find(x=>x.open),key=String((open||seasons[0])?.dataset.r513r2Node||''),asset=assetFor(key);if(asset)put(parent.querySelector(':scope > summary'),asset,'parent')}return true};
 const observer=new MutationObserver(()=>queueMicrotask(patch));observer.observe(document.documentElement,{childList:true,subtree:true});document.addEventListener('toggle',event=>{if(event.target?.matches?.('details[data-r513r2-node^="gauntlet-season:"]'))queueMicrotask(patch)},true);queueMicrotask(patch);globalThis.__SMASHDUMP_R81_GAUNTLET_BANNER_ADAPTER__={marker,patch,assetFor,seasonAssets};})();
/* SMASHDUMP_R72_CURRENT_ONLY_CARD_PRESENTATION_ADAPTER */
(()=>{'use strict';const marker='SMASHDUMP_R72_CURRENT_ONLY_CARD_PRESENTATION_ADAPTER';if(globalThis.__SMASHDUMP_R72_CARD_ADAPTER__)return;
 const current=()=>{const s=globalThis.__SMASHDUMP_ENCYCLOPEDIA_ACTIVE_SNAPSHOT__;return s&&!(/frozen/i.test(String(s.kind||s.app_mode||''))||s.data_root_mode==='accepted_root')};
 const patch=root=>{if(!current())return;const scope=root||document,all=(selector)=>[...(scope.matches?.(selector)?[scope]:[]),...(scope.querySelectorAll?.(selector)||[])];all('.thumb img.entity-thumb-image').forEach(img=>{img.classList.remove('entity-thumb-image');img.classList.add('entity-card-image')})};
 const observer=new MutationObserver(records=>{for(const r of records)for(const n of r.addedNodes)if(n.nodeType===1)patch(n)});observer.observe(document.documentElement,{childList:true,subtree:true});patch();setInterval(()=>patch(document),500);globalThis.__SMASHDUMP_R72_CARD_ADAPTER__={marker,patch};})();
/* SMASHDUMP_CANDIDATE_SEARCH_SCOPE_SHIM_R1 */
(()=>{'use strict';
 const MARKER='SMASHDUMP_CANDIDATE_SEARCH_SCOPE_SHIM_R1';
 const selected=()=>globalThis.__SMASHDUMP_ENCYCLOPEDIA_ACTIVE_SNAPSHOT__;
 const frozen=s=>!!s&&(s.data_root_mode==='accepted_root'||/frozen/i.test(String(s.kind||''))||/frozen/i.test(String(s.app_mode||'')));
 const install=()=>{const snapshot=selected();if(!snapshot||frozen(snapshot))return false;
  const prior=globalThis.searchTextFor,nameOf=globalThis.nameOf;if(typeof prior!=='function'||typeof nameOf!=='function')return false;
  if(prior.__smashdumpCandidateSearchScopeOwner===MARKER)return true;
  const scoped=function(entity){if(entity?.category==='enemies'){const current=(entity?.current&&typeof entity.current==='object')?entity.current:((entity?.baseline&&typeof entity.baseline==='object')?entity.baseline:{}),aliases=Array.isArray(current.search_aliases)?current.search_aliases:[];return [nameOf(entity),...aliases].filter(v=>v!==null&&v!==undefined&&String(v).trim()).join(' ').toLowerCase()}return prior(entity)};
  Object.defineProperty(scoped,'__smashdumpCandidateSearchScopeOwner',{value:MARKER});globalThis.searchTextFor=scoped;
  globalThis.__SMASHDUMP_CANDIDATE_SEARCH_SCOPE__={marker:MARKER,enemy_name_search_scope:'name_and_aliases_only',other_categories:'accepted_r26_c4_search_owner'};return true};
 document.addEventListener('load',event=>{const target=event.target,snapshot=selected();if(!snapshot||frozen(snapshot)||!(target instanceof HTMLScriptElement))return;const renderer=String(snapshot.renderer_file||'');if(!renderer)return;let loaded;try{loaded=new URL(target.src,location.href)}catch{return}if(loaded.pathname.endsWith('/'+renderer))queueMicrotask(install)},true);
})();
/* SMASHDUMP_ENCYCLOPEDIA_SOURCE_CONTRACT_REPAIR_R8_1_LOADER */
(async()=>{'use strict';
 const appRoot=new URL('.',location.href),report=(message,error)=>console.error('SMASHDUMP_ENCYCLOPEDIA_SOURCE_CONTRACT_REPAIR_R8_1',message,error||'');
 const add=(name,done)=>{const script=document.createElement('script');script.src=new URL(name,appRoot).href+'?source_contract_r8_1=1';script.async=false;script.onload=done||null;script.onerror=e=>report(`Could not load ${name}`,e);document.head.appendChild(script);return script};
 const stable=()=>{const label=document.getElementById('versionLabel'),nav=document.getElementById('categoryNav'),list=document.getElementById('entityList'),text=String(document.body?.textContent||'');return Boolean(label&&nav&&list&&String(label.textContent||'').trim()&&!/^Loading(?:…|\.\.\.)?$/i.test(String(label.textContent||'').trim())&&nav.childElementCount>0&&!/Could not load Encyclopedia data|Encyclopedia failed to load/.test(text))};
 const selector=()=>{let loaded=false;const start=()=>{if(loaded||!stable())return false;loaded=true;observer.disconnect();clearTimeout(timer);add('snapshot_ui_source_contract_r8_1.js');return true},observer=new MutationObserver(()=>queueMicrotask(start)),timer=setTimeout(()=>{observer.disconnect();if(!loaded)report('Renderer did not reach a stable shell; selector was not injected.')},180000);observer.observe(document.documentElement,{childList:true,subtree:true,characterData:true});start()};
 try{
  const outer=globalThis.__SMASHDUMP_ENCYCLOPEDIA_SNAPSHOT_REGISTRY__;if(!outer||!Array.isArray(outer.snapshots))throw Error('Snapshot registry unavailable');
  const params=new URLSearchParams(location.search),wanted=params.get('ency_snapshot')||localStorage.getItem('smashdump.encyclopedia.snapshot.r8_1')||localStorage.getItem('smashdump.encyclopedia.snapshot.r8')||outer.default_snapshot;
  const selected=outer.snapshots.find(r=>r.id===wanted&&r.selectable!==false)||outer.snapshots.find(r=>r.id===outer.default_snapshot&&r.selectable!==false)||outer.snapshots.find(r=>r.selectable!==false);if(!selected)throw Error('No selectable snapshot');
  const frozen=selected.data_root_mode==='accepted_root'||/frozen/i.test(String(selected.kind||''))||/frozen/i.test(String(selected.app_mode||'')),dataRoot=frozen?new URL('data/',appRoot):new URL(`data/versions/${encodeURIComponent(selected.storage_key)}/`,appRoot);
  let base=document.head.querySelector('base[data-smashdump-snapshot]');if(frozen)base?.remove();else{if(!base){base=document.createElement('base');base.dataset.smashdumpSnapshot='1';document.head.prepend(base)}base.href=dataRoot.href}
  localStorage.setItem('smashdump.encyclopedia.snapshot.r8_1',selected.id);globalThis.__SMASHDUMP_ENCYCLOPEDIA_ACTIVE_SNAPSHOT__=selected;globalThis.__SMASHDUMP_ENCYCLOPEDIA_DATA_ROOT__=dataRoot.href;
  const original=globalThis.fetch.bind(globalThis),contractName=frozen?'dynamic_registry_frozen_r8_1.json':'dynamic_registry_current_r8_1.json',contractResponse=await original(new URL(`data/${contractName}`,appRoot).href,{cache:'no-store'});if(!contractResponse.ok)throw Error(`Dynamic registry contract HTTP ${contractResponse.status}`);const inherited=await contractResponse.json();if(inherited?.schema!=='smashdump.encyclopedia.dynamic_registry.v4')throw Error(`Unexpected inherited dynamic registry schema ${inherited?.schema}`);
  globalThis.fetch=(input,init)=>{const href=typeof input==='string'?input:(input instanceof URL?input.href:(input&&input.url)||'');let resolved;try{resolved=new URL(href,appRoot)}catch{resolved=null}
   if(resolved&&(resolved.pathname==='/api/encyclopedia/versions'||resolved.pathname.endsWith('/encyclopedia_dynamic_registry_cache.json')))return Promise.resolve(new Response(JSON.stringify(inherited),{status:200,headers:{'Content-Type':'application/json','X-SmashDump-Registry-Contract':'dynamic-v4'}}));
   if(typeof input==='string'&&/^data\/(?!versions\/)/.test(input))input=new URL(input.slice(5),dataRoot).href;else if(resolved&&resolved.origin===location.origin&&/\/data\/(?!versions\/)/.test(resolved.pathname)){const suffix=resolved.pathname.split('/data/').slice(1).join('/data/');const next=new URL(suffix+resolved.search,dataRoot);input=input instanceof Request?new Request(next.href,input):next.href}return original(input,init)};
  const renderer=String(selected.renderer_file||'');if(!renderer||renderer.includes('/')||renderer.includes('\\'))throw Error('Selected snapshot has no safe renderer_file');add(renderer,selector);
 }catch(error){report('Source-contract loader failed',error)}
})();
